### ISSUE TITLE
Unable to import pygpu

### ISSUE THREAD

**Issue by linbaiwpi** [mrakgr/Tutorials#1]
Hello
This is a nice article, I followed it and it works fine until Step 6
As you mentioned "Lastly, add cuda0 to the DEVICE environment variable and you should be able to do import pygpu and then pygpu.test() to run the tests in Cuda mode. GPUARRAY_DEVICE variable does nothing unlike what the documentation states." 

After generating the gpuarray.lib/dll files, and add '/lib/release" as environment variable, I still cannot import pygpu in python. Can you please guide me out of this? 

Thanks

**Comment by mrakgr** [comment]
> Can you please guide me out of this?

No, sorry. 

I wrote this tutorial over a year ago and then never touched Theano or Python again. Since February, I've been working on a language for the sake of making my own ML library, so I have no interest in different ML libraries.

I am decently sure that if you look around, you should be able to find more up to date material on installing Theano. A year is a long time in ML terms since the field moves so quickly. Also, since then there have been new developments like CNTK and Tensorflow getting Windows support so I suggest you look into that as well if you cannot get Theano to work.

I wish you the best of luck.
